sudo: false
language: node_js
node_js: '5'
addons:
  postgresql: '9.4'
before_script:
- bash install.sh
script:
- source env.sh && npm run test
notifications:
  slack: devops-training-spb:kfjTXFxdFQxyBbAJ0UtYVqOe
deploy:
  provider: heroku
  api_key:
    secure: Fijtbx7PDorCl3X81Yu4jbAQGTz8a/3tDijuD6p5lBk7r5W360VbrbLJCYoub1C0oqQJKzlrVsp//AYqCECiY5JR7oPxeYnK8K+368U/uQOZvW+xTh+uzsJ/SPxqf6yN1TLwDlj5dlEt6L8oEWRgs+YAg9zO6JzgJhlT977Qnbt2rOyA6ksRo7jn2Lwm6KXBGKUyOae0kI4O6+0LupARDjGLASoQoDN05kdJ20XxnhPjvx5B6RXcFn55w/UzID6KTGuJ3dj29XFRpOrwCIBs7vs75lP2ARLdNY+jPNY2EchPFSEVaMUK0fn6PpGH1GatIqibqssNFKJHMLvSnS+F6lw0YF/A6gK6wuJd+wWCaMAq9PU03PxvuER9MU8Nk6cvYoovbQTcWAgCe3pKDbvkznWkhTmrq/BBVtwshDoZFRr2kDWQ5vnY1rj0jhks0y0CytUKRaWYjTLjfdjWwWD9Zk0NTbU5hcs1Ns4744Ms1k8d8cxyCO9Fv6WxzCmAfXGDLFMLF7E9IDexTJozbEJYHRRMGWH9YN8XwsEDSUUsY1YjslFWF41XRINl45RRUL97XgZG1/ceacZhQ2v4c1XkwT0nlnAa779zWn3KJ/3gMCoTMRL82s8YFnV9IcKaBI9AhxwFhyao98BwEu/rnSUZMj92OofXwa0FRnKga1ZDU1A=
